name: Release

on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  note:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Gren
        run: npm install github-release-notes -g

      - name: Create a release
        run: gren release --username=minami110 --repo=githubactiontest --tags=${GITHUB_REF#refs/tags/}
        env:
          GREN_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
